name: Deploy frontend to Firebase Hosting

inputs:
  channelId:
    required: false
    default: ""
    type: string
  backendUrl:
    required: true
  oauthClientId:
    required: true
  repoToken:
    required: true
  firebaseServiceAccount:
    required: true
  projectId:
    required: true

runs:
    using: composite
    steps:
      - run: echo "REACT_APP_BACKEND_URL=${{ inputs.backendUrl }}" > .env
        shell: bash
      - run: echo "REACT_APP_OAUTH_CLIENT_ID=${{ inputs.oauthClientId }}" >> .env
        shell: bash
      - run: rm -rf node_modules && yarn install --frozen-lockfile && yarn build
        shell: bash
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: "${{ inputs.channelId }}"
          entryPoint: ./frontend
          repoToken: "${{ inputs.repoToken }}"
          firebaseServiceAccount: "${{ inputs.firebaseServiceAccount }}"
          projectId: "${{ inputs.projectId }}"
