name: Deploy backend to Heroku

inputs:
  email:
    required: true
  apiKey:
    required: true
  appName:
    required: true
  databaseUrl:
    required: true
  firebaseApiKey:
    required: true
  firebaseRequestUri:
    required: true
  firebaseBucket:
    required: true
  firebaseProject:
    required: true
  firebasePrivateKey:
    required: true
  firebaseEmail:
    required: true
  mailerUser:
    required: true
  mailerId:
    required: true
  mailerSecret:
    required: true
  mailerRefreshToken:
    required: true

runs:
    using: composite
    steps:
      - name: Set Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $INPUT_EMAIL
              password $INPUT_API_KEY
            machine git.heroku.com
              login $INPUT_EMAIL
              password $INPUT_API_KEY
          EOF
        shell: bash
      - name: Add Heroku git remote
        run: heroku git:remote --app $INPUT_APP_NAME
        shell: bash
      - name: Set Heroku config vars
        run: |
          config() {
            value_var="$2"
            if [ -z "$value_var" ]; then
              value_var="$1"
            fi
            value_var="INPUT_$value_var"
            value="${!value_var}"
            heroku config:set "$1" "$value" -a "$INPUT_APP_NAME"
          }
          config MG_DATABASE_URL DATABASE_URL
          config FIREBASE_WEB_API_KEY FIREBASE_API_KEY
          config FIREBASE_REQUEST_URI
          config FIREBASE_STORAGE_DEFAULT_BUCKET FIREBASE_BUCKET
          config FIREBASE_PROJECT_ID FIREBASE_PROJECT
          config FIREBASE_SVC_ACCOUNT_PRIVATE_KEY FIREBASE_PRIVATE_KEY
          config FIREBASE_SVC_ACCOUNT_CLIENT_EMAIL FIREBASE_EMAIL
          config MAILER_USER
          config MAILER_CLIENT_ID MAILER_ID
          config MAILER_CLIENT_SECRET MAILER_SECRET
          config MAILER_REFRESH_TOKEN
          heroku config:set PREVIEW_DEPLOY=true -a $INPUT_APP_NAME
        shell: bash
      - name: Push to Heroku
        run: git subtree push --prefix backend heroku main
        shell: bash
