name: Deploy frontend to Firebase Hosting preview

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository && github.base_ref == 'main' }}"
    uses: ./.github/workflows/common-firebase-deploy.yml
    secrets:
      backendUrl: "${{ secrets.DEV_BACKEND_URL }}"
      oauthClientId: "${{ secrets.DEV_OAUTH_CLIENT_ID }}"
      repoToken: "${{ secrets.GITHUB_TOKEN }}"
      firebaseServiceAccount: "${{ secrets.DEV_FIREBASE_SVC_ACCOUNT_ROWAN_HOUSE_SOCIETY }}"
      projectId: "${{ secrets.DEV_FIREBASE_PROJECT_ID }}"
