name: Deploy frontend and backend to production
on: workflow_dispatch
jobs:
  build_and_deploy_frontend:
    environment: prod
    uses: ./.github/workflows/common-firebase-deploy.yml
    with:
      channelId: live
    secrets:
      backendUrl: "${{ secrets.PROD_BACKEND_URL }}"
      oauthClientId: "${{ secrets.PROD_OAUTH_CLIENT_ID }}"
      repoToken: "${{ secrets.GITHUB_TOKEN }}"
      firebaseServiceAccount: "${{ secrets.PROD_FIREBASE_SVC_ACCOUNT_JSON }}"
      projectId: "${{ secrets.PROD_FIREBASE_PROJECT_ID }}"
