name: Production: Deploy all
on: workflow_dispatch
jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    environment: rhs-prod
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/firebase-deploy
        with:
          channelId: live
          backendUrl: "${{ secrets.PROD_BACKEND_URL }}"
          oauthClientId: "${{ secrets.PROD_OAUTH_CLIENT_ID }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.PROD_FIREBASE_SVC_ACCOUNT_JSON }}"
          projectId: "${{ secrets.PROD_FIREBASE_PROJECT_ID }}"
  deploy_backend:
    runs-on: ubuntu-latest
    environment: rhs-prod
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/heroku-deploy
        with:
          email: "${{ secrets.PROD_HEROKU_EMAIL }}"
          apiKey: "${{ secrets.PROD_HEROKU_API_KEY }}"
          appName: "${{ secrets.PROD_HEROKU_PROJECT_ID }}"
          databaseUrl: "${{ secrets.PROD_MG_DATABASE_URL }}"
          firebaseApiKey: "${{ secrets.PROD_FIREBASE_WEB_API_KEY }}"
          firebaseRequestUri: "${{ secrets.PROD_FIREBASE_REQUEST_URI }}"
          firebaseBucket: "${{ secrets.PROD_FIREBASE_STORAGE_DEFAULT_BUCKET }}"
          firebaseProject: "${{ secrets.PROD_FIREBASE_PROJECT_ID }}"
          firebasePrivateKey: "${{ secrets.PROD_FIREBASE_SVC_ACCOUNT_PRIVATE_KEY }}"
          firebaseEmail: "${{ secrets.PROD_FIREBASE_SVC_ACCOUNT_CLIENT_EMAIL }}"
          mailerUser: "${{ secrets.PROD_MAILER_USER }}"
          mailerId: "${{ secrets.PROD_MAILER_CLIENT_ID }}"
          mailerSecret: "${{ secrets.PROD_MAILER_CLIENT_SECRET }}"
          mailerRefreshToken: "${{ secrets.PROD_MAILER_REFRESH_TOKEN }}"
