name: "Staging: Deploy backend"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: rhs-staging
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/heroku-deploy
        with:
          email: "${{ secrets.DEV_HEROKU_EMAIL }}"
          apiKey: "${{ secrets.DEV_HEROKU_API_KEY }}"
          appName: "${{ secrets.DEV_HEROKU_PROJECT_ID }}"
          databaseUrl: "${{ secrets.DEV_MG_DATABASE_URL }}"
          firebaseApiKey: "${{ secrets.DEV_FIREBASE_WEB_API_KEY }}"
          firebaseRequestUri: "${{ secrets.DEV_FIREBASE_REQUEST_URI }}"
          firebaseBucket: "${{ secrets.DEV_FIREBASE_STORAGE_DEFAULT_BUCKET }}"
          firebaseProject: "${{ secrets.DEV_FIREBASE_PROJECT_ID }}"
          firebasePrivateKey: "${{ secrets.DEV_FIREBASE_SVC_ACCOUNT_PRIVATE_KEY }}"
          firebaseEmail: "${{ secrets.DEV_FIREBASE_SVC_ACCOUNT_CLIENT_EMAIL }}"
          mailerUser: "${{ secrets.DEV_MAILER_USER }}"
          mailerId: "${{ secrets.DEV_MAILER_CLIENT_ID }}"
          mailerSecret: "${{ secrets.DEV_MAILER_CLIENT_SECRET }}"
          mailerRefreshToken: "${{ secrets.DEV_MAILER_REFRESH_TOKEN }}"
