name: Deploy frontend to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build_and_deploy:
    uses: ./.github/workflows/common/firebase-deploy.yml
    with:
      channelId: live
    secrets:
      backendUrl: "${{ secrets.DEV_BACKEND_URL }}"
      oauthClientId: "${{ secrets.DEV_OAUTH_CLIENT_ID }}"
      repoToken: "${{ secrets.GITHUB_TOKEN }}"
      firebaseServiceAccount: "${{ secrets.DEV_FIREBASE_SVC_ACCOUNT_ROWAN_HOUSE_SOCIETY }}"
      projectId: "${{ secrets.DEV_FIREBASE_PROJECT_ID }}"
